### ISSUE TITLE
Задача N тел: выход на орбиту

### ISSUE THREAD

**Issue by avasyukov** [arsen-davtyan/ex2oop#1]
Фиксирую факт. На семинаре не удалось получить картинку, в которой спутник находится на круговой орбите. Нужно разобраться.

**Comment by arsen-davtyan** [comment]
Сделано: задача "вывести тело на орбиту" реализуется закоммиченным исходником.

**Comment by avasyukov** [comment]
Стало очень правдоподобно, но я пока не уверен, что до конца правильно.

Для вот таких тел:
```c++
    vector<body> myBodies;
    myBodies.push_back(body(1000, 2, -5, 0, 0, 0));
    myBodies.push_back(body(1, 1, 5, 0, 0, 10));
```

Картинка вот такая - https://youtu.be/JyI8opR8Gxo

Я ожидал круговую орбиту, но я тоже могу быть где-то неправ. Так что ещё контрольно смотрим - и Вы, и я.

**Comment by arsen-davtyan** [comment]
Произошло странное. Я решил забить на a_pot и переписать все так, как было в первый раз. Удивительно, но оно заработало. Думаю в самой первой версии у меня там была какая-то ошибка в формулах.

**Comment by avasyukov** [comment]
> Думаю в самой первой версии у меня там была какая-то ошибка в формулах.

Думаю, так и было. Посмотрел diff текущей версии и первой (слава гиту, что это можно просто сделать). Таки да, вот оно значимое отличие:
```c++
-        vx += ax;
-        vy += ay;
+        vx += ax * dt;
+        vy += ay * dt;
```

Итого - тикет решён. Тело вышло на круговую орбиту - https://youtu.be/LyptKU5B1t0. И на эллиптическую при скорости 12 вместо 10 тоже вышло - https://youtu.be/9gZGlzfVZp0.

Плиз, дочистите #2, то в целом это уже вин.
